name: Houses
version: 1.0
description: Combines Plots + Houses to create an amazing combination!
main: me.jet315.houses.Core
depend: [PlotSquared]
softdepend: [TokenManager,Vault]
commands:
  house:
    description: The base command for the House's plugin
    aliases: [h,houses,home]